### ISSUE TITLE
Need openedx.yaml files

### ISSUE THREAD

**Issue by nedbat** [edx/edx-cookiecutters#14]
Both for this repo, and for the repos that it creates.

**Comment by jinder1s** [comment]
Openedx yaml for this repo: https://github.com/edx/edx-cookiecutters/blob/master/openedx.yaml
openedx yaml for repos it creates: https://github.com/edx/edx-cookiecutters/blob/master/python-template/%7B%7Bcookiecutter.placeholder_repo_name%7D%7D/openedx.yaml
