### ISSUE TITLE
Legal considerations are different for different orgs

### ISSUE THREAD

**Issue by nedbat** [edx/edx-cookiecutters#308]
A/C

- [ ] Cookiecutter asks what org the repo is being made in
- [ ] Repos made in the edx org no longer say "Contributions welcome"
- [ ] Repos made in the edx org direct people to email security@**edx**.org
- [ ] Review READMEs for each type and either resolve or make tickets for resolving any remaining issues

The cookiecutters currently say things like "Contributions welcome" and "email security@openedx.org".  Repos made in the edx GitHub organization need different details.

Possible implementation:
Have orgs add a cookiecutter file to .github that has the information that should go in this part of the repo

**Comment by jmbowman** [comment]
Mild preference for specifying the org so people don't need to know how different orgs are set up, but may need to ask more specific questions if tCRIL isn't happy about edx-org-specific conditionals in the code.

**Comment by nedbat** [comment]
Other things in the README:
- The organization is hardcoded in many places
- The instructions to how to finish the README includes "openedx" as an organization
- Should we point edx-org repos to discuss.openedx.org for discussions? Probably not.
- Should we point them to the Open edX slack workspace? Probably not.
- Ditto the openedx.org getting-help page
- What about the Open edX code of conduct?
- _**Maybe we should just stick to the legal issues.**_

**Comment by nedbat** [comment]
I made a wiki page with the things to change: https://openedx.atlassian.net/wiki/spaces/COMM/pages/3779493907/Repo+deltas+for+edx+GitHub+repos
